### ISSUE TITLE
neo4j包用的是哪个版本的呀，我这一直No module named 'neo4j'

### ISSUE THREAD

**Issue by baobaotql** [xlorne/QASystemOnMedicalKG#4]
![image](https://github.com/xlorne/QASystemOnMedicalKG/assets/40971441/9f5bf91b-bad3-45ac-9fb4-ef35f73401f8)

![image](https://github.com/xlorne/QASystemOnMedicalKG/assets/40971441/1fbd4b5f-c3ca-4fd8-9aed-788e60ab53ce)

**Comment by xlorne** [comment]
应该是你的开发工具运行的环境和命令行的环境没有不一致，你确认一下吧，你的错误不是版本不对，是没有找到这个模块
